baseURL = "https://backslashn.com/"
languageCode = "en-gb"
title = "\\n â€” @adurdin is thinking aloud"
theme = "temple"
copyright = "<a rel='license' href='http://creativecommons.org/licenses/by-nc/4.0/'>CC BY-NC 4.0</a>."

# Enables Chroma-based syntax highlighting with theme "friendly"
# See https://xyproto.github.io/splash/docs/ for other theme options
pygmentsStyle = "friendly"

# If true, Chroma will highlight GitHub-style code fences in addition to
# highlight shortcodes
pygmentsCodeFences = true


[params]
# Enables the topmenu, which pulls from categories
topmenu = "categories"

# Enables custom date format (optional, the default is MM-DD-YYYY)
# For reference to date and time templating, see:
# https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
dateformatpretty = "2006-01-02"

# Enable table of contents, this can be overridden by page level parameter `toc`.
toc = true


[taxonomies]
# Builds a list page for each category given
post = "post"
tag = "tag"
category = "category"


[author]
name = "Andy Durdin"
#github = "adurdin"
email = "me@andy.durdin.net"
twitter = "@adurdin"
#medium = "mediumUsername"


#[menu]
#
#[[menu.nav]]
#name = "All posts"
#url = "post/"
#weight = 1
#
## [[menu.nav]]
## name = "About"
## url = "about/"
## weight = 2
##
## [[menu.nav]]
## name = "Tags"
## url = "tags/"
## weight = 3
##
## [[menu.nav]]
## name = "Categories"
## url = "categories/"
## weight = 4
##
## [[menu.nav]]
## name = "RSS"
## url = "index.xml"
## weight = 5
#